// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:04729571-6df2-4f1e-8211-df55ff6cd89c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_X9ACyKOKe",
    "aws_user_pools_web_client_id": "4929ta90sgj81bdo0beuu2lsn0",
    "oauth": {}
};


export default awsmobile;
